/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TalentFeedbacksRouteImport } from './routes/talent-feedbacks'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingFormRouteImport } from './routes/onboarding-form'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MooVerifiedRouteImport } from './routes/moo-verified'
import { Route as MooTalentFormRouteImport } from './routes/moo-talent-form'
import { Route as MooTalentRouteImport } from './routes/moo-talent'
import { Route as MooCircleRouteImport } from './routes/moo-circle'
import { Route as ClientFeedbacksRouteImport } from './routes/client-feedbacks'
import { Route as BccRouteImport } from './routes/bcc'
import { Route as IndexRouteImport } from './routes/index'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentFeedbacksRoute = TalentFeedbacksRouteImport.update({
  id: '/talent-feedbacks',
  path: '/talent-feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFormRoute = OnboardingFormRouteImport.update({
  id: '/onboarding-form',
  path: '/onboarding-form',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MooVerifiedRoute = MooVerifiedRouteImport.update({
  id: '/moo-verified',
  path: '/moo-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const MooTalentFormRoute = MooTalentFormRouteImport.update({
  id: '/moo-talent-form',
  path: '/moo-talent-form',
  getParentRoute: () => rootRouteImport,
} as any)
const MooTalentRoute = MooTalentRouteImport.update({
  id: '/moo-talent',
  path: '/moo-talent',
  getParentRoute: () => rootRouteImport,
} as any)
const MooCircleRoute = MooCircleRouteImport.update({
  id: '/moo-circle',
  path: '/moo-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientFeedbacksRoute = ClientFeedbacksRouteImport.update({
  id: '/client-feedbacks',
  path: '/client-feedbacks',
  getParentRoute: () => rootRouteImport,
} as any)
const BccRoute = BccRouteImport.update({
  id: '/bcc',
  path: '/bcc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bcc': typeof BccRoute
  '/client-feedbacks': typeof ClientFeedbacksRoute
  '/moo-circle': typeof MooCircleRoute
  '/moo-talent': typeof MooTalentRoute
  '/moo-talent-form': typeof MooTalentFormRoute
  '/moo-verified': typeof MooVerifiedRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-form': typeof OnboardingFormRoute
  '/privacy': typeof PrivacyRoute
  '/talent-feedbacks': typeof TalentFeedbacksRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bcc': typeof BccRoute
  '/client-feedbacks': typeof ClientFeedbacksRoute
  '/moo-circle': typeof MooCircleRoute
  '/moo-talent': typeof MooTalentRoute
  '/moo-talent-form': typeof MooTalentFormRoute
  '/moo-verified': typeof MooVerifiedRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-form': typeof OnboardingFormRoute
  '/privacy': typeof PrivacyRoute
  '/talent-feedbacks': typeof TalentFeedbacksRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bcc': typeof BccRoute
  '/client-feedbacks': typeof ClientFeedbacksRoute
  '/moo-circle': typeof MooCircleRoute
  '/moo-talent': typeof MooTalentRoute
  '/moo-talent-form': typeof MooTalentFormRoute
  '/moo-verified': typeof MooVerifiedRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-form': typeof OnboardingFormRoute
  '/privacy': typeof PrivacyRoute
  '/talent-feedbacks': typeof TalentFeedbacksRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bcc'
    | '/client-feedbacks'
    | '/moo-circle'
    | '/moo-talent'
    | '/moo-talent-form'
    | '/moo-verified'
    | '/onboarding'
    | '/onboarding-form'
    | '/privacy'
    | '/talent-feedbacks'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bcc'
    | '/client-feedbacks'
    | '/moo-circle'
    | '/moo-talent'
    | '/moo-talent-form'
    | '/moo-verified'
    | '/onboarding'
    | '/onboarding-form'
    | '/privacy'
    | '/talent-feedbacks'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/bcc'
    | '/client-feedbacks'
    | '/moo-circle'
    | '/moo-talent'
    | '/moo-talent-form'
    | '/moo-verified'
    | '/onboarding'
    | '/onboarding-form'
    | '/privacy'
    | '/talent-feedbacks'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BccRoute: typeof BccRoute
  ClientFeedbacksRoute: typeof ClientFeedbacksRoute
  MooCircleRoute: typeof MooCircleRoute
  MooTalentRoute: typeof MooTalentRoute
  MooTalentFormRoute: typeof MooTalentFormRoute
  MooVerifiedRoute: typeof MooVerifiedRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingFormRoute: typeof OnboardingFormRoute
  PrivacyRoute: typeof PrivacyRoute
  TalentFeedbacksRoute: typeof TalentFeedbacksRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-feedbacks': {
      id: '/talent-feedbacks'
      path: '/talent-feedbacks'
      fullPath: '/talent-feedbacks'
      preLoaderRoute: typeof TalentFeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-form': {
      id: '/onboarding-form'
      path: '/onboarding-form'
      fullPath: '/onboarding-form'
      preLoaderRoute: typeof OnboardingFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moo-verified': {
      id: '/moo-verified'
      path: '/moo-verified'
      fullPath: '/moo-verified'
      preLoaderRoute: typeof MooVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moo-talent-form': {
      id: '/moo-talent-form'
      path: '/moo-talent-form'
      fullPath: '/moo-talent-form'
      preLoaderRoute: typeof MooTalentFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moo-talent': {
      id: '/moo-talent'
      path: '/moo-talent'
      fullPath: '/moo-talent'
      preLoaderRoute: typeof MooTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moo-circle': {
      id: '/moo-circle'
      path: '/moo-circle'
      fullPath: '/moo-circle'
      preLoaderRoute: typeof MooCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-feedbacks': {
      id: '/client-feedbacks'
      path: '/client-feedbacks'
      fullPath: '/client-feedbacks'
      preLoaderRoute: typeof ClientFeedbacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bcc': {
      id: '/bcc'
      path: '/bcc'
      fullPath: '/bcc'
      preLoaderRoute: typeof BccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BccRoute: BccRoute,
  ClientFeedbacksRoute: ClientFeedbacksRoute,
  MooCircleRoute: MooCircleRoute,
  MooTalentRoute: MooTalentRoute,
  MooTalentFormRoute: MooTalentFormRoute,
  MooVerifiedRoute: MooVerifiedRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingFormRoute: OnboardingFormRoute,
  PrivacyRoute: PrivacyRoute,
  TalentFeedbacksRoute: TalentFeedbacksRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
